var hierarchy =
[
    [ "com.khao.PoorDeal.dto.ActionType", "enumcom_1_1khao_1_1_poor_deal_1_1dto_1_1_action_type.html", null ],
    [ "com.khao.PoorDeal.dto.AddCommentRequest", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_add_comment_request.html", null ],
    [ "com.khao.PoorDeal.dto.AddPostRequest", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_add_post_request.html", null ],
    [ "com.khao.PoorDeal.controller.AuthController", "classcom_1_1khao_1_1_poor_deal_1_1controller_1_1_auth_controller.html", null ],
    [ "com.khao.PoorDeal.service.AuthService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_auth_service.html", null ],
    [ "com.khao.PoorDeal.domain.Comment", "classcom_1_1khao_1_1_poor_deal_1_1domain_1_1_comment.html", null ],
    [ "com.khao.PoorDeal.dto.CommentAndRepliesResponse", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_comment_and_replies_response.html", null ],
    [ "com.khao.PoorDeal.mapper.CommentMapper", "interfacecom_1_1khao_1_1_poor_deal_1_1mapper_1_1_comment_mapper.html", null ],
    [ "com.khao.PoorDeal.repository.CommentRepository", "classcom_1_1khao_1_1_poor_deal_1_1repository_1_1_comment_repository.html", null ],
    [ "com.khao.PoorDeal.dto.CommentResponse", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_comment_response.html", null ],
    [ "com.khao.PoorDeal.domain.CommentStatus", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_comment_status.html", null ],
    [ "com.khao.PoorDeal.domain.Mail", "classcom_1_1khao_1_1_poor_deal_1_1domain_1_1_mail.html", null ],
    [ "com.khao.PoorDeal.controller.MailController", "classcom_1_1khao_1_1_poor_deal_1_1controller_1_1_mail_controller.html", null ],
    [ "com.khao.PoorDeal.mapper.MailMapper", "interfacecom_1_1khao_1_1_poor_deal_1_1mapper_1_1_mail_mapper.html", null ],
    [ "com.khao.PoorDeal.repository.MailRepository", "classcom_1_1khao_1_1_poor_deal_1_1repository_1_1_mail_repository.html", null ],
    [ "com.khao.PoorDeal.dto.MailResponse", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_mail_response.html", null ],
    [ "com.khao.PoorDeal.service.MailService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_mail_service.html", null ],
    [ "com.khao.PoorDeal.dto.MailSummary", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_mail_summary.html", null ],
    [ "com.khao.PoorDeal.domain.Member", "classcom_1_1khao_1_1_poor_deal_1_1domain_1_1_member.html", null ],
    [ "com.khao.PoorDeal.mapper.MemberMapper", "interfacecom_1_1khao_1_1_poor_deal_1_1mapper_1_1_member_mapper.html", null ],
    [ "com.khao.PoorDeal.repository.MemberRepository", "classcom_1_1khao_1_1_poor_deal_1_1repository_1_1_member_repository.html", null ],
    [ "com.khao.PoorDeal.domain.MemberRole", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_member_role.html", null ],
    [ "com.khao.PoorDeal.service.MemberService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_member_service.html", null ],
    [ "com.khao.PoorDeal.domain.ParentType", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_parent_type.html", null ],
    [ "com.khao.PoorDeal.dto.PointChargeRequest", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_point_charge_request.html", null ],
    [ "com.khao.PoorDeal.domain.Post", "classcom_1_1khao_1_1_poor_deal_1_1domain_1_1_post.html", null ],
    [ "com.khao.PoorDeal.controller.PostController", "classcom_1_1khao_1_1_poor_deal_1_1controller_1_1_post_controller.html", null ],
    [ "com.khao.PoorDeal.mapper.PostMapper", "interfacecom_1_1khao_1_1_poor_deal_1_1mapper_1_1_post_mapper.html", null ],
    [ "com.khao.PoorDeal.repository.PostRepository", "classcom_1_1khao_1_1_poor_deal_1_1repository_1_1_post_repository.html", null ],
    [ "com.khao.PoorDeal.dto.PostResponse", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_post_response.html", null ],
    [ "com.khao.PoorDeal.dto.PostSearchCondition", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_post_search_condition.html", null ],
    [ "com.khao.PoorDeal.service.PostService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_post_service.html", null ],
    [ "com.khao.PoorDeal.dto.PostSummary", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_post_summary.html", null ],
    [ "com.khao.PoorDeal.domain.PostType", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_post_type.html", null ],
    [ "com.khao.PoorDeal.dto.ProcessActionRequest", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_process_action_request.html", null ],
    [ "com.khao.PoorDeal.domain.ProcessStatus", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_process_status.html", null ],
    [ "com.khao.PoorDeal.domain.ProcessType", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_process_type.html", null ],
    [ "com.khao.PoorDeal.domain.Report", "classcom_1_1khao_1_1_poor_deal_1_1domain_1_1_report.html", null ],
    [ "com.khao.PoorDeal.controller.ReportController", "classcom_1_1khao_1_1_poor_deal_1_1controller_1_1_report_controller.html", null ],
    [ "com.khao.PoorDeal.mapper.ReportMapper", "interfacecom_1_1khao_1_1_poor_deal_1_1mapper_1_1_report_mapper.html", null ],
    [ "com.khao.PoorDeal.repository.ReportRepository", "classcom_1_1khao_1_1_poor_deal_1_1repository_1_1_report_repository.html", null ],
    [ "com.khao.PoorDeal.dto.ReportRequest", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_report_request.html", null ],
    [ "com.khao.PoorDeal.dto.ReportResponse", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_report_response.html", null ],
    [ "com.khao.PoorDeal.service.ReportService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_report_service.html", null ],
    [ "com.khao.PoorDeal.domain.ReportStatus", "enumcom_1_1khao_1_1_poor_deal_1_1domain_1_1_report_status.html", null ],
    [ "com.khao.PoorDeal.service.S3Service", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_s3_service.html", null ],
    [ "SimpleUrlAuthenticationFailureHandler", null, [
      [ "com.khao.PoorDeal.exception.CustomAuthFailureHandler", "classcom_1_1khao_1_1_poor_deal_1_1exception_1_1_custom_auth_failure_handler.html", null ]
    ] ],
    [ "com.khao.PoorDeal.dto.StartProcessRequest", "classcom_1_1khao_1_1_poor_deal_1_1dto_1_1_start_process_request.html", null ],
    [ "com.khao.PoorDeal.controller.TradeController", "classcom_1_1khao_1_1_poor_deal_1_1controller_1_1_trade_controller.html", null ],
    [ "com.khao.PoorDeal.mapper.TradeMapper", "interfacecom_1_1khao_1_1_poor_deal_1_1mapper_1_1_trade_mapper.html", null ],
    [ "com.khao.PoorDeal.repository.TradeRepository", "classcom_1_1khao_1_1_poor_deal_1_1repository_1_1_trade_repository.html", null ],
    [ "com.khao.PoorDeal.service.TradeService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_trade_service.html", null ],
    [ "UserDetailsService", null, [
      [ "com.khao.PoorDeal.service.AuthDetailsService", "classcom_1_1khao_1_1_poor_deal_1_1service_1_1_auth_details_service.html", null ]
    ] ]
];